name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v1
      
      # Set up Node.js 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      # Install dependencies
      - run: npm install
      
      # Build the Gatsby site
      - run: npm run build
      
      # Deploy to GitHub Pages
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
