name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js (using version 16 for compatibility)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      # Step 4: Build the Gatsby site
      - name: Build Gatsby site
        run: yarn run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      # Step 5: Deploy using Gatsby GitHub Pages action
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
