name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (use a compatible version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Remove package-lock.json to avoid conflicts
      - name: Remove package-lock.json
        run: rm -f package-lock.json

      # Step 4: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 5: Build the Gatsby site
      - name: Build Gatsby site
        run: yarn run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy Gatsby to GitHub Pages
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
